import Link from "next/link";
import { notFound } from "next/navigation";
import { ImageGallery } from "@/components/ImageLightbox";
import { VideoPreview } from "@/components/VideoModal";
import { works } from "@/data/works";
import { assetUrl } from "@/lib/assets";
export function generateStaticParams() { return works.map((work) => ({ slug: work.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const work = works.find((item) => item.slug === slug); return { title: work?.title ?? "作品" }; }
export default async function WorkDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const work = works.find((item) => item.slug === slug); if (!work) notFound(); return <article className="detail"><header className="detail-header"><p className="eyebrow">{work.category}</p><h1>{work.title}</h1><p>{work.summary}</p><div className="detail-facts"><span>{work.duration}</span><span>{work.previewVideo ? "点击播放作品节选" : "图片项目"}</span></div></header><div className="detail-media">{work.previewVideo ? <VideoPreview cover={work.cover} title={work.title} source={work.previewVideo} /> : work.gallery.length ? <img src={assetUrl(work.cover)} alt={work.title} /> : <VideoPreview cover={work.cover} title={work.title} />}</div><section className="detail-section detail-columns"><div><p className="eyebrow">RESPONSIBILITIES</p><h2>我的职责</h2><ul>{work.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="eyebrow">TOOLS</p><h2>使用工具</h2><ul>{work.tools.map((item) => <li key={item}>{item}</li>)}</ul></div></section>{work.gallery.length > 0 && <section className="detail-section"><p className="eyebrow">GALLERY</p><h2>项目画面</h2><ImageGallery images={work.gallery} alt={work.title} /></section>}<Link className="back-link" href="/works/">← 返回作品列表</Link></article>; }
