export type VideoPreview = { previewVideo?: string; poster?: string; previewDurationLabel?: string; needsReview: boolean; };

// Generated by scripts/video-previews.mjs. Do not expose source paths in UI.
export const videoPreviews: Record<string, VideoPreview> = {
  "video-production-01": {
    "previewVideo": "/assets/works/video-production/video-production-01.mp4",
    "poster": "/assets/works/video-production/video-production-01.webp",
    "previewDurationLabel": "25 秒作品节选",
    "needsReview": true
  },
  "video-production-02": {
    "previewVideo": "/assets/works/video-production/video-production-02.mp4",
    "poster": "/assets/works/video-production/video-production-02.webp",
    "previewDurationLabel": "25 秒作品节选",
    "needsReview": true
  },
  "video-production-03": {
    "previewVideo": "/assets/works/video-production/video-production-03.mp4",
    "poster": "/assets/works/video-production/video-production-03.webp",
    "previewDurationLabel": "23 秒作品节选",
    "needsReview": true
  },
  "video-production-04": {
    "previewVideo": "/assets/works/video-production/video-production-04.mp4",
    "poster": "/assets/works/video-production/video-production-04.webp",
    "previewDurationLabel": "25 秒作品节选",
    "needsReview": true
  },
  "video-production-05": {
    "previewVideo": "/assets/works/video-production/video-production-05.mp4",
    "poster": "/assets/works/video-production/video-production-05.webp",
    "previewDurationLabel": "25 秒作品节选",
    "needsReview": true
  },
  "video-packaging-01": {
    "previewVideo": "/assets/works/video-packaging/video-packaging-01.mp4",
    "poster": "/assets/works/video-packaging/video-packaging-01.webp",
    "previewDurationLabel": "25 秒作品节选",
    "needsReview": true
  },
  "video-packaging-02": {
    "previewVideo": "/assets/works/video-packaging/video-packaging-02.mp4",
    "poster": "/assets/works/video-packaging/video-packaging-02.webp",
    "previewDurationLabel": "25 秒作品节选",
    "needsReview": true
  }
};
